/*
 * Don't edit this file by hand!
 * This file was generated from a npm-package using gulp. 
 * For more information see gulpfile.js in the project root
 */
define(function (require, exports, module) {// Generated by CoffeeScript 1.8.0
(function() {
  var BaseGlyphRecord, LayerRecord, r;

  r = require('restructure');

  LayerRecord = new r.Struct({
    gid: r.uint16,
    paletteIndex: r.uint16
  });

  BaseGlyphRecord = new r.Struct({
    gid: r.uint16,
    firstLayerIndex: r.uint16,
    numLayers: r.uint16
  });

  module.exports = new r.Struct({
    version: r.uint16,
    numBaseGlyphRecords: r.uint16,
    baseGlyphRecord: new r.Pointer(r.uint32, new r.Array(BaseGlyphRecord, 'numBaseGlyphRecords')),
    layerRecords: new r.Pointer(r.uint32, new r.Array(LayerRecord, 'numLayerRecords')),
    numLayerRecords: r.uint16
  });

}).call(this);

});
