/*
 * Don't edit this file by hand!
 * This file was generated from a npm-package using gulp. 
 * For more information see gulpfile.js in the project root
 */
define(function (require, exports, module) {// Generated by CoffeeScript 1.8.0
(function() {
  var r;

  r = require('restructure');

  module.exports = new r.Struct({
    instructions: new r.Array(r.uint8)
  });

}).call(this);

});
