/*
 * Don't edit this file by hand!
 * This file was generated from a npm-package using gulp. 
 * For more information see gulpfile.js in the project root
 */
define(function (require, exports, module) {// Generated by CoffeeScript 1.8.0
(function() {
  var GaspRange, r;

  r = require('restructure');

  GaspRange = new r.Struct({
    rangeMaxPPEM: r.uint16,
    rangeGaspBehavior: new r.Bitfield(r.uint16, ['grayscale', 'gridfit', 'symmetricSmoothing', 'symmetricGridfit'])
  });

  module.exports = new r.Struct({
    version: r.uint16,
    numRanges: r.uint16,
    gaspRanges: new r.Array(GaspRange, 'numRanges')
  });

}).call(this);

});
