/*
 * Don't edit this file by hand!
 * This file was generated from a npm-package using gulp. 
 * For more information see gulpfile.js in the project root
 */
define(function (require, exports, module) {// Generated by CoffeeScript 1.8.0
(function() {
  var HmtxEntry, r;

  r = require('restructure');

  HmtxEntry = new r.Struct({
    advanceWidth: r.uint16,
    leftSideBearing: r.int16
  });

  module.exports = new r.Struct({
    metrics: new r.Array(HmtxEntry, function() {
      return this.parent.hhea.numberOfMetrics;
    }),
    leftSideBearings: new r.Array(r.int16, function() {
      return this.parent.maxp.numGlyphs - this.parent.hhea.numberOfMetrics;
    })
  });

}).call(this);

});
