/*
 * Don't edit this file by hand!
 * This file was generated from a npm-package using gulp. 
 * For more information see gulpfile.js in the project root
 */
define(function (require, exports, module) {// Generated by CoffeeScript 1.8.0
(function() {
  var VerticalOrigin, r;

  r = require('restructure');

  VerticalOrigin = new r.Struct({
    glyphIndex: r.uint16,
    vertOriginY: r.int16
  });

  module.exports = new r.Struct({
    majorVersion: r.uint16,
    minorVersion: r.uint16,
    defaultVertOriginY: r.int16,
    numVertOriginYMetrics: r.uint16,
    metrics: new r.Array(VerticalOrigin, 'numVertOriginYMetrics')
  });

}).call(this);

});
